# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5480a635ccbe41c15a6c27135d5f97b399f81a1ec5681654a4f27a470b40d8717bdc7fb9faecf2d3cf051633768968da0bc66915c199eedaecb112c4a0b72f4

test:
  secret_key_base: 45b335dd1d2f7ef467b087338a0ca9be9ccd619677e14f16283a1ebf564bd398e05b7b7c902863882d3f355ef6e95fc823586e03a0eef78e4098c6dc2eed439e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
